### ISSUE TITLE
The default transaction and snapshot dir /tmp/zookeeper are removed after reboot

### ISSUE THREAD

**Issue by timoschmidt** [SimpleFinance/chef-exhibitor#12]
When you use the default configuration zookeeper does not come up after reboot again because the 
transaction and snapshot dir is lost. Shouldn't the startup script check if they exist and create them when they are missing?

**Comment by jeffbyrnes** [comment]
@timoschmidt the encouragement would be to change these values to somewhere more permanent, as you'l going to want this files to stick around.

I don't recall the reason why these paths were initially chosen, but I know it extends all the way back to when this cookbook was part of [SimpleFinance/chef-zookeeper](https://github.com/SimpleFinance/chef-zookeeper) (pre-v2.0.0).

We wrap this cookbook, and change those directories in our wrapper cookbook’s attributes:

```ruby
set['exhibitor']['snapshot_dir'] = '/mnt/zookeeper'
set['exhibitor']['transaction_dir'] = '/mnt/zookeeper'
set['exhibitor']['log_index_dir'] = '/mnt/zookeeper_log_indexes'
```

**Comment by jeffbyrnes** [comment]
Closing, no response.

**Comment by williamsjj** [comment]
This problem just bit me after a reboot. Took me awhile to figure out why a node didn't come up. It would be a good idea to set this to a saner location.

**Comment by jeffbyrnes** [comment]
@williamsjj what would you suggest as a more sensible location? At the least, I’ll update the README to be sure this is mentioned, for now.
