### ISSUE TITLE
Please submit to supermarket.chef.io

### ISSUE THREAD

**Issue by ankurcha** [SimpleFinance/chef-exhibitor#16]
Using directly from the repository is a bit clunky and it would be great if the maintainers could create a release and push to supermarket.chef.io

**Comment by jeffbyrnes** [comment]
:+1: on this. I've got contributor rights here, but do not have the ability to push a release to the Supermarket.

The current state of this cookbook is “good enough” to use. Additional improvements can be incremental.

**Comment by ankurcha** [comment]
:bow:

**Comment by jakedavis** [comment]
@jeffbyrnes, oh? That is a bug I think. I'll see if I can fix that today ...

To be honest I still have not figured out how personally to push a cookbook to the Supermarket :/

**Comment by jeffbyrnes** [comment]
@jakedavis simplest way I've found is to just use [Stove](https://github.com/sethvargo/stove). Failing that, check out the [`knife cookbook site` docs](https://docs.chef.io/knife_cookbook_site.html).

**Comment by jakedavis** [comment]
Okay, so ... Stove doesn't work for me:

```
{"error_code"=>"INVALID_DATA", "error_messages"=>["The metadata is formatted incorrectly.", "Multipart POST part 'tarball' must contain a non-empty README."]}
```

The README is non-empty so I have no clue on this. `knife cookbook site share` claims I do not have a cookbook called `exhibitor` even though my cookbook path points to the right directory and the directory and metadata both say `exhibitor`.

At this point, I really do not care whose account it's under if someone else wants to upload it (the cookbook does not presently exist on the supermarket). This is probably for the best anyway as we (at Simple, that is) do not use the supermarket at all and thus are probably not the best equipped here.

**Comment by jeffbyrnes** [comment]
@jakedavis man, that is frustrating. I'll see about publishing it and granting you access.

**Comment by jeffbyrnes** [comment]
And published: https://supermarket.chef.io/cookbooks/exhibitor

@jakedavis my copy of Stove worked w/o any issues. Here's the commands I used:

```
$ git checkout v0.4.0
$ stove --no-git --username jeffbyrnes --key ~/.chef/jeffbyrnes.pem 
```

**Comment by jakedavis** [comment]
Thanks @jeffbyrnes, I appreciate it. I'm guessing in that case then that it is my knife.rb that is not comprehensive enough or something. I'll see soon here about generating a new one or reading some docs on it. I can try `--no-git` too.

**Comment by jeffbyrnes** [comment]
@jakedavis mm, very possible. We have a _heavily_ populated `knife.rb` that we use; it's based on what the [starter Chef repo](https://github.com/chef/chef-repo) used to contain. Might be handy to use Chef DK to generate a fresh Chef repo, and see what that `knife.rb` looks like (if it creates one at all).
