### ISSUE TITLE
Error executing action `start` on resource 'runit_service[exhibitor]'

### ISSUE THREAD

**Issue by tb01923** [SimpleFinance/chef-exhibitor#22]
I am running into this running centOS 6.5.  Although it looks like everything installsand starts up OK - but it would be nice if the cookbook didn't fail.

================================================================================
10.6.20.87     Error executing action `start` on resource 'runit_service[exhibitor]'
10.6.20.87     ================================================================================
10.6.20.87     
10.6.20.87     Mixlib::ShellOut::ShellCommandFailed
10.6.20.87     ------------------------------------
10.6.20.87     Expected process to exit with [0], but received '1'
10.6.20.87     ---- Begin output of /sbin/sv start /etc/service/exhibitor ----
10.6.20.87     STDOUT: warning: /etc/service/exhibitor: unable to open supervise/ok: file does not exist
10.6.20.87     STDERR: 
10.6.20.87     ---- End output of /sbin/sv start /etc/service/exhibitor ----
10.6.20.87     Ran /sbin/sv start /etc/service/exhibitor returned 1

Possibly related to this:

https://github.com/hw-cookbooks/runit/issues/142

If so let's close this, but I wanted post incase they are not related (still learning chef).

**Comment by jeffbyrnes** [comment]
@tb01923 I’ve encountered this before as well, and hw-cookbooks/runit#142 covers it exactly. Glad to see they’ve shipped a fix! A simple `berks update` should fix you up.

If not, please re-open & we’ll investigate.
