### ISSUE TITLE
dependency is out of date

### ISSUE THREAD

**Issue by spuder** [SimpleFinance/chef-exhibitor#23]
The zookeeper cookbook was bumped to 3.0.0, however the metadata in this cookbook is still referencing ~> 2.0

This means that I can't have my wrapper cookbook point to 3.0.0 if I want it to install both zookeeper and exhibitor

**Comment by spuder** [comment]
As outlined in issue #9 the dependencies are conflicting. 

An alternative fix would be to backport the fix from the 3.0.0 cookbook back to the 2.x.x cookbook.

**Comment by eropple** [comment]
It strikes me that maybe that backport and re-versioning would be a safer way to do this resolving #9 here (maybe that becomes a major version bump?). I got bushwacked today by this bug when I had to rebuild a cluster with 3.4.7 being out and my solution at the moment involves chef-rewind and prayer. :(

**Comment by jeffbyrnes** [comment]
I’ll get this sorted today.

**Comment by jeffbyrnes** [comment]
@eropple the issue there is that would potentially upgrade people’s deployed instances of ZooKeeper, which is potentially breaking.

Fix for this incoming.
